apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cstemplate.fullname" . }}-config
  labels:
    {{- include "cstemplate.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.app.environment | quote }}
  ASPNETCORE_URLS: {{ .Values.app.aspnetcoreUrls | quote }}

